export enum GenderPreference {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  NO_PREFERENCE = 'NO_PREFERENCE',

  //MALE, FEMALE, NO_PREFERENCE
}

export enum RoomType {
  SINGLE = 'SINGLE',
  DOUBLE = 'DOUBLE',
  SUITE = 'SUITE',
  STUDIO = 'STUDIO',

  //SINGLE, DOUBLE, SUITE, STUDIO
}

export enum PropertyType {
  APARTMENT = 'APARTMENT',
  VILLA = 'VILLA',
  CONDO = 'CONDO',
  HOUSE = 'HOUSE',
  SHARED_HOUSE = 'SHARED_HOUSE',
  TOWNHOUSE = 'TOWNHOUSE',
  COMMERCIAL = 'COMMERCIAL',
  
  //APARTMENT, VILLA, CONDO, HOUSE, SHARED_HOUSE, TOWNHOUSE, COMMERCIAL
}

export enum RoomStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  HIDDEN = 'HIDDEN',

  //AVAILABLE, RENTED, HIDDEN
}



